# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MovieSearcher' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks

  # Pods for MovieSearcher
  pod 'Alamofire', '4.8.1'
  pod 'AlamofireImage', '3.5.0'
  
  target 'MovieSearcherTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MovieSearcherUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
